config/routes.rb
Blog::Application.routes.draw do
  get "app/index"
  get "welcome/index"
  
  root 'welcome#index'
  
  resources :posts do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  http_basic_authenticate_with name: 'dhh', password: 'secret', only: :destroy

  def index
    @post = Post.find(params.require(:post_id))

    respond_to do |format|
      format.json { render json: @post.comments }
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  #http_basic_authenticate_with name: 'dhh', password: 'secret',
  #except: [:index, :show]
  
  def index
    @posts = Post.all

    respond_to do |format|
      format.json { render json: @posts }
      format.html { render 'posts/index' }
    end
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    
    respond_to do |format|
      if @post.save
        format.json { render json: @post, status: :created, location: @post }
        format.html { redirect_to @post }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.html { render 'posts/new' }
      end
    end

  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.json { render json: @post }
      format.html { redirect_to posts_path }
    end
  end

  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.json { render json: @post }
      format.html { render 'posts/show' }
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(params[:post].permit(:title, :text))
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	  #session[:user] = 'tubo'
    #
	  #if session[:user]
  	#	render :text => session.inspect
	  #else
		 # render :text => 'nie ma'
	  #end
  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/app/index.html.erb
<!--<script src="/assets/app.js"></script>-->
<h1>App#index</h1>

<div id="posts">

</div>
<div>
  <button id="add-post">Add post</button>
</div>

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
</p>

<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>
<p>
    <%= link_to 'Destroy Comment', [comment.post, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :commenter %><br />
        <%= f.text_field :commenter %>
    </p>
    <p>
        <%= f.label :body %><br />
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", controller_name %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, remote: true do |f| %>
  <% if @post and @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    
    <% @posts.each do |post| %>
        <tr>
            <td><%= post.title %></td>
            <td><%= post.text %></td>
            <td><%= link_to 'Show', post_path(post.id) %></td>
            <td><%= link_to 'Edit', edit_post_path(post)%></td>
            <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure' } %></td>
        </tr>
    <% end %>
</table>

<%= link_to 'New post', new_post_path %>

<!--<div id="posts"></div>

<script type="text/javascript">
  $(function() {
    // Blog is the app name
    window.router = new Blog.Routers.PostsRouter({posts: <%= @posts.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>-->

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @post.text %>
</p>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
    <%= render comment %>
<% end %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', posts_path %>
<%= link_to 'Edit', edit_post_path(@post)%>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= @session %>
<%= link_to "My Blog", controller: "posts" %>